### ISSUE TITLE
XP orbs cause crash

### ISSUE THREAD

**Issue by rdomloge** [LunaPixelStudios/Better-Minecraft#225]
### Describe the Bug

When I kill mobs, the little XP orbs cause my server to crash when they are absorbed by my player. The server has the following in the log

[22:56:21] [Server thread/WARN]: Failed to handle packet for /10.42.2.0:52990
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.nbt.CompoundTag.m_128435_(CompoundTag.java:237) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.nbt.CompoundTag.m_128425_(CompoundTag.java:246) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.nbt.CompoundTag.m_128461_(CompoundTag.java:324) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.m_182446_(EnchantmentHelper.java:54) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44843_(EnchantmentHelper.java:71) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44839_(EnchantmentHelper.java:290) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]
	at net.minecraft.world.entity.ExperienceOrb.m_147092_(ExperienceOrb.java:220) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]

This line is replicated for 1000s of lines, then

[22:56:21] [Server thread/INFO]: [gamertag] lost connection: Internal server error
[22:56:21] [Server thread/INFO]: [gamertag] left the game

Once this happens, it is impossible to rejoin the server (the error reoccurs when loading terrain and I am disconnected. The only way I can rejoin the game is if I execute the following command:

rcon-cli kill @e[type=experience_orb]

This is a fairly recent development - I have been playing for weeks without this happening and acruing experience without issue. Now though, I can recreate this easily by:

### Reproduction Steps

1. Do something to get XP
2. XP orb comes toward player
3. When player touches XP orb, player is kicked from server and server errors.

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SharkieTV** [comment]
Hi, 1.18.1 is not in development anymore, I am focusing on 1.18.2 so their will probably be no update for it. If I had a guess it would be some sort of enchantment on your gear. can you please provide me the gear and the enchantments thank

**Comment by rdomloge** [comment]
Interesting! I have a backpack with repairman and a pickaxe in the backpack with vein mining, otherwise all my other enchantments are vanilla. I'll try without the backpack and see what difference that makes.

**Comment by rdomloge** [comment]
OK, so I took the backpack off and the problem ceased. I then disenchanted the backpack and put it back on, the problem was still resolved. So it seems to be related to the repairman enchantment. Thanks for the tip!
