### ISSUE TITLE
Problem while I Oppened

### ISSUE THREAD

**Issue by Miguerines** [LunaPixelStudios/Better-Minecraft#257]
### Describe the Bug

irst at all, I am not a native speaker, so, my English level is not perfect
Now, When I donwloaded BetterMinecraft, for playing alone, I put all the mods on the mods file on .Minecraft But when I ttried to enter, there was a problem, IDK why or how, only I could not enter, I tried donwload another Forge version, but it hadn`t solve the problem, so, I want some help with that, I think, is important tto know that I play minecraft since another launcher called Tlauncher
[Launcher] Minecraft closed with exit code: 1

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @1a500561; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1a500561) 	at MC-BOOTSTRAP/fmlloader@1.18.2-40.0.32/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43) 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138) 	... 13 more Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @1a500561; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1a500561) 	at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Server Pack [FORGE] v5

### Optifine

No

**Comment by SharkieTV** [comment]
TLauncher is illegal and wont help with it, dont use the serverpack use Curseforge launcher with a real MC Account
