### ISSUE TITLE
server wont start

### ISSUE THREAD

**Issue by damver** [LunaPixelStudios/Better-Minecraft#300]
### Describe the Bug

hey, i run my server with pterodactyl. and i get this error...

i have tried to run it on ubuntu and i have the same.. any ideas?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx6144M -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
[15:46:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.0.17, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220228.144236]
[15:46:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Oracle Corporation
[15:46:08] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[15:46:10] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge, forge, forge, forge, forge, forge, forge, forge, forge, forge, forge, forge
[15:46:21] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[15:46:21] [main/ERROR] [mixin/]: Mixin config biomemakeover-common.mixins.json does not specify "minVersion" property
[15:46:21] [main/ERROR] [mixin/]: Mixin config biomemakeover-forge.mixins.json does not specify "minVersion" property
[15:46:21] [main/ERROR] [mixin/]: Mixin config friendsandfoes-common.mixins.json does not specify "minVersion" property
[15:46:21] [main/ERROR] [mixin/]: Mixin config radium.mixins.json does not specify "minVersion" property
[15:46:21] [main/ERROR] [mixin/]: Mixin config radon.mixins.json does not specify "minVersion" property
[15:46:22] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[15:46:23] [main/INFO] [Radium/]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
[15:46:25] [main/WARN] [ferritecore-mixin/]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[15:46:25] [main/WARN] [mixin/]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.0.17/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @4b74b35; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @4b74b35)
        at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:138)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:59)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
        at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:109)
        ... 13 more
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:8a7ff71a924b07e8ad3ff6309705f9ea26d3780fcddff87f4197273bcdc634f1 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx6144M -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
container@pterodactyl~ Server marked as stopping...

### Operating System

ubuntu

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v6

### Optifine

No

**Comment by SharkieTV** [comment]
Use the proper Serverpack and its files, you are trying to run Forge 40.0.17

**Comment by damver** [comment]
i downloaded the lastest files from curseforge for the server. and curseforge says 40.0.17 it uses.
what version do i need then??
