### ISSUE TITLE
Server error message

### ISSUE THREAD

**Issue by Kortopii** [LunaPixelStudios/Better-Minecraft#311]
Hello, 

I am getting the following error when trying to launch the server package that I downloaded through curse forge.
Any idea what the problem is? I could not find anything on google.

Thank you :)

forge.jar present. Moving on...
minecraft_server."1.16.5".jar present. Moving on...
User did not agree to Mojang's EULA.
eula.txt present. Moving on...
Starting server...
Minecraft version: "1.16.5"
Forge version: "36.2.29"
Java version:
java 18.0.1 2022-04-19
Java(TM) SE Runtime Environment (build 18.0.1+10-24)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1+10-24, mixed mode, sharing)
Java args:
2022-04-26 21:00:52,353 main WARN Advanced terminal features are not available in this environment
[21:00:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.29, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[21:00:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.1 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x7fc2413d) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x7fc2413d
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Press any key to continue . . .

**Comment by SharkieTV** [comment]
Uninstall java 18 you need java 8 to run it

**Comment by Kortopii** [comment]
> 
Thanks for the reply, I uninstalled java 18 and reinstalled java 8 from the java.com website but I get this error message now. Is there a download link for Java 8 someone could point me to?


Forge server present. Moving on...
Minecraft server present. Moving on...
User did not agree to Mojang's EULA.
eula.txt present. Moving on...
Starting server...
Minecraft version: "1.18.2"
Forge version: "40.0.54"
Java version:
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Java args in user_jvm_args.txt: "-Xmx5G"
If you receive the error message "Error: Could not find or load main class @user_jvm_args.txt" you may be using the wrong Java-version for this modded Minecraft server. Contact the modpack-developer or, if you made the server pack yourself, do a quick google-search for the used Minecraft version to find out which Java-version is required in order to run this server.
Error: Could not find or load main class @user_jvm_args.txt
Press any key to continue . . .

Here's an image of the java version i have
![image](https://user-images.githubusercontent.com/104460652/165504994-88dedc39-bbac-4b33-a3a1-83e50d2f5ee5.png)

**Comment by SharkieTV** [comment]
The fist log is about 1.16.5 now your sending a log about 1.18.2?
If you want to play 1.18.2 then you need to install java 17
If you want to play 1.16.5 then you need to remove Javas above 11 for it to work
