### ISSUE TITLE
Server crashes going into Nether

### ISSUE THREAD

**Issue by jaamesrone** [LunaPixelStudios/Better-Minecraft#44]
### Describe the Bug

My girlfriend and I recently started playing Better Minecraft 1.18 and we even got the recommended server to get. Whenever we first go into the Nether the server crashed. We get the achievement every time the server restarts, we'll be in the nether for about 30 seconds, then everything just freezes but we're still able to break blocks, no loot drop and not open any chest. I'll provide screenshots and videos, the server is currently restarting.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

[Crash Report.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7902056/Crash.Report.txt)

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft 1.18

### Optifine

No

**Comment by jaamesrone** [comment]
---- Minecraft Crash Report ----
[20.01 01:52:38] [Server] // Don't be sad. I'll do better next time, I promise!
[20.01 01:52:38] [Server] Time1/20/22, 1:52 AM
[20.01 01:52:38] [Server] DescriptionWatching Server
[20.01 01:52:38] [Server] java.lang.ErrorServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
[20.01 01:52:38] [Server] 	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?] {}
[20.01 01:52:38] [Server] 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252) ~[?:?] {}
[20.01 01:52:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:146) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:136) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:132) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.Level.m_6522_(Level.java:170) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:122) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,re:mixin,re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.Level.m_6325_(Level.java:165) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.Level.m_8055_(Level.java:390) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.block.TripWireHookBlock.m_57685_(TripWireHookBlock.java:107) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.block.TripWireBlock.m_57610_(TripWireBlock.java:87) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.block.TripWireBlock.m_6810_(TripWireBlock.java:67) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60753_(BlockBehaviour.java:671) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:236) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,re:classloading,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccess,pl:mixin:APP:supplementaries.mixins.json:LevelChunkMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.LevelChunkAddEntityMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:244) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:blocks.FlowingFluidAccessor,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.LavaFluid.m_6364_(LavaFluid.java:181) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:146) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:blocks.FlowingFluidAccessor,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.FlowingFluid.m_76010_(FlowingFluid.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:blocks.FlowingFluidAccessor,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:410) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,re:classloading,pl:mixin:APP:the_bumblezone.mixins.json:blocks.FlowingFluidAccessor,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:73) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:478) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,re:classloading,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccess,pl:mixin:APP:supplementaries.mixins.json:LevelChunkMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.LevelChunkAddEntityMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkMap.m_199393_(ChunkMap.java:650) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkMap$$Lambda$13426/0x0000000802667820.apply(Unknown Source) ~[?:?] {}
[20.01 01:52:38] [Server] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2329!/:?] {}
[20.01 01:52:38] [Server] 	at com.mojang.datafixers.util.Either.flatMap(Either.java:191) ~[datafixerupper-4.0.26.jar%2329!/:?] {}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkMap.m_199387_(ChunkMap.java:648) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkMap$$Lambda$13146/0x0000000802624ae8.apply(Unknown Source) ~[?:?] {}
[20.01 01:52:38] [Server] 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
[20.01 01:52:38] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter$$Lambda$13194/0x000000080262f460.run(Unknown Source) ~[?:?] {}
[20.01 01:52:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:530) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:538) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading}
[20.01 01:52:38] [Server] 	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
[20.01 01:52:38] [Server] 	at net.minecraft.server.MinecraftServer$$Lambda$12465/0x00000008024efa60.run(Unknown Source) ~[?:?] {}
[20.01 01:52:38] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by KhanhPham05** [comment]
please put your log into a paste tool and put the log link to `Crash Report or Log` section please

**Comment by jaamesrone** [comment]
> please put your log into a paste tool and put the log link to `Crash Report or Log` section please

how do i do that?

**Comment by switchnlade** [comment]
Copy and paste your log into a site like [pastebin](https://pastebin.com/). This makes it a lot easier to read without having to download anything.

**Comment by SharkieTV** [comment]
@jaamesrone remove the serene seasons mod and lmk

**Comment by jaamesrone** [comment]
> 

we ended switching to 1.16.5 just because they are so much many mods than 1.18. Its seems to be doing fine, we can go to the nether. Sometimes the server will randomly crash but thats fine.

**Comment by switchnlade** [comment]
Well, do you have a crash log for those 'random' crashes? Just to see if there's an issue? We'd rather not have crashes if they are preventable
