### ISSUE TITLE
Better Minecraft server not starting

### ISSUE THREAD

**Issue by Arvicii** [LunaPixelStudios/Better-Minecraft#454]
running start.sh on Linux prints this on the terminal:
~/ForgeServer$ ./start.sh
forge.jar present. Moving on...
minecraft_server.1.16.5.jar present. Moving on...
eula.txt present. Moving on...
Starting server...
Minecraft version: 1.16.5
Forge version: 36.2.29
Java version:
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
Java args: 
[12:33:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.29, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[12:33:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.3 by Private Build
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x62bd2070) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x62bd2070
	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
	
What should I do?

**Comment by SharkieTV** [comment]
uninstall java 17, java 8 is required to run 1.16.5
