### ISSUE TITLE
Geode+ mod is breaking End Dimension

### ISSUE THREAD

**Issue by Thangkou** [LunaPixelStudios/Better-Minecraft#493]
### Describe the Bug

Crashing because of the Geode+ mod. Removing this mod makes The End work perfectly fine.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/3/22, 7:13 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{geode:wrappist_block}
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[server-1.18.2-20220404.173914-srg.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.yeoxuhang.geode.block.BuddingWrappistBlock.m_7455_(BuddingWrappistBlock.java:47) ~[Geode+_v1.0.1+1.18.2.jar%23115!/:1.0] {re:classloading}

### Reproduction Steps

1. Go to The End
2. find loaded in chunk that uses Geode+ mod
3. will eventually crash

### Crash Report or Log

https://pastebin.com/ddELtgB1

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

better minecraft 11.5

### Optifine

No

### Other Mods

Infernal Mobs
Twilight Forest

**Comment by SharkieTV** [comment]
fixed in v12
